### ISSUE TITLE
Provide a way to pass-in the name of the "input parameter" and calling file

### ISSUE THREAD

**Issue by GuyPaddock** [leeoniya/dump_r.php#51]
I'm working on a Drupal logging module that wraps dump_r. For that module, `dump_r` is actually getting invoked by the logging API. Consequently, I'd love it if it would be possible for the code that detects the calling file and the name of the variable being passed-in to `dump_r` was a bit more configurable and/or a separate component.

Right now, it always logs the name of the variable the logging API uses to print a value, instead of the name  of the variable passed-in to the logger. In addition, the calling file ends up always being `Logger.php` instead of the actual caller in the code invoking the Logger.

**Comment by leeoniya** [comment]
i don't really want to grow the API, so maybe the easiest thing to do here it to add a global config option that disables dump_r from showing the trace info?

**Comment by GuyPaddock** [comment]
Actually, yeah, that'd be ideal. Right now, we're relying on some code to search & replace the incorrect trace info with some info we sniff out ourselves (effectively, our code is doing the same thing as `dump_r`, but with a different blacklist of files to ignore in the stack). So, an option to turn off the built-in support for `dump_r` to generate this info would be more efficient.

**Comment by leeoniya** [comment]
added. try it out.

**Comment by GuyPaddock** [comment]
Only downside with this approach is that you're still reflecting on the stack backtrace to get the information that may or may not be rendered, no?

I also noticed that `Core` uses `debug_backtrace()`, without passing `DEBUG_BACKTRACE_IGNORE_ARGS`, so it's getting a lot more information about the stack than it needs. I believe if you omit the args, it should reduce memory usage and improve performance of what is normally a decently heavy operation.

**Comment by leeoniya** [comment]
i've added `DEBUG_BACKTRACE_IGNORE_ARGS` and moved the `debug_backtrace()` call out of `Core::dump_r()` into the global `dump_r()` wrapper. feel free to implement your own version of the global `dump_r()` on top of `Core::dump_r()`.

see https://github.com/leeoniya/dump_r.php/commit/b75b5e9946a2b055cbf651eb6d646d69d1666e1f

**Comment by GuyPaddock** [comment]
Thank you!
