### ISSUE TITLE
Multiple dump_r's on a single line breaks variable name output

### ISSUE THREAD

**Issue by alystair** [leeoniya/dump_r.php#52]
```php
print_r($_SESSION);
print_r($_COOKIE);
```
Outputs the following correctly 
![image](https://user-images.githubusercontent.com/159109/42735731-5390e448-8827-11e8-94b1-9d7fc0bac12c.png)

However this... 
`print_r($_SESSION); print_r($_COOKIE);`
Does this...
![image](https://user-images.githubusercontent.com/159109/42735740-7235d200-8827-11e8-87b4-97d11cf5cfaa.png)

Output different headers

**Comment by leeoniya** [comment]
hey @alystair 

i'm not sure this is something that can be fixed. dump_r uses PHP's `debug_backtrace()` [1] to figure out the variable passed into dump_r [2]. however, this function only returns line-level detail, so there's no way to know which specific invocation it's working in.

if you have any ideas, let me know.

[1] http://php.net/manual/en/function.debug-backtrace.php
[2] https://github.com/leeoniya/dump_r.php/blob/master/dump_r.php#L16

**Comment by alystair** [comment]
Good to know - I guess that also explains why doing something like `print_r([$_SESSION,$_COOKIE]);` produces weird output. Maybe PHP should add a \_\_CHAR__ magic constant so we know more than just \_\_LINE__ ;)

**Comment by leeoniya** [comment]
lol `__CHAR__` :D

as for `print_r([$_SESSION,$_COOKIE]);`, that sound like it can be fixed with a more thorough regex, but it's probably not worh chasing all the edge cases since you'll end up reproducing a poor man's PHP parser that handles any expression typed literally into dump_r .

**Comment by alystair** [comment]
Makes sense. Thanks for the rapid response!
